Master/WebUi/Controllers/AdminController.cs
using System;
using GalaSoft.MvvmLight.Ioc;
using System.Threading.Tasks;
using System.Web.Mvc;
using Server.Infrastructure.Dto.Requests.User;
using WebUi.Model.User;
using WebUiServiceClient.User;
using DataAccessLayer;

namespace WebUi.Controllers
{
    public class AdminController : Controller
    {
        private IUserServiceClient _userServiceClient;
        private IUserServiceClient UserServiceClient => _userServiceClient ?? (_userServiceClient = SimpleIoc.Default.GetInstance<IUserServiceClient>());

        // GET
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Info()
        {
            var user = new UserViewModel();

            if (Session["User"] != null)
            {
                try
                {
                    var result = await UserServiceClient.GetUserByEmail(Session["User"].ToString());

                    user.Name = result.Name;
                    user.Email = result.Email;
                    user.Phone = result.Phone;
                    user.RoleName = Enum.GetName(typeof(RoleTypeEnum), result.RoleId).ToString();
                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                }
            }

            return View(user);
        }

        public async Task<ActionResult> EditUser()
        {
            var user = new UserViewModel();

            if (Session["User"] != null)
            {
                try
                {
                    var result = await UserServiceClient.GetUserByEmail(Session["User"].ToString());

                    user.Id = result.Id;
                    user.Name = result.Name;
                    user.Email = result.Email;
                    user.Phone = result.Phone;
                    user.RoleName = result.RoleName;
                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                }
            }

            return View(user);
        }

        [HttpPost]
        public async Task<ActionResult> EditUser(UserViewModel model)
        {
            var request = new AddUserRequest
            {
                Id = model.Id,
                Name = model.Name,
                Email = model.Email,
                Phone = model.Phone,
                Password = model.Password
            };

            try
            {
                var result = await UserServiceClient.EditUser(request);

                ViewBag.Message = "Done :)";
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }

            return View();
        }
    }
}

Master/WebUi/Controllers/AdminPermissionController.cs
using GalaSoft.MvvmLight.Ioc;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebUi.Model.Permission;
using WebUiServiceClient.Permission;

namespace WebUi.Controllers
{
    public class AdminPermissionController : Controller
    {
        private IPermissionServiceClient _permissionServiceClient;
        private IPermissionServiceClient PermissionServiceClient => _permissionServiceClient ?? (_permissionServiceClient = SimpleIoc.Default.GetInstance<IPermissionServiceClient>());

        // GET: AdminPermission
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> PermissionList()
        {
            var model = new PermissionModel();

            try
            {
                model.PermissionList = await PermissionServiceClient.GetAllPermission();
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }
            return View(model);
        }

        public async Task<ActionResult> AddNewPermission()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> AddNewPermission(PermissionModel model)
        {
            try
            {
                await PermissionServiceClient.AddPermission(model.Id, model.Key, model.PermissionTypeId);

                return RedirectToAction("PermissionList");
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }
            return View();
        }

        public async Task<ActionResult> EditPermission(long id)
        {
            var permission = new PermissionModel();

            try
            {
                var result = await PermissionServiceClient.GetPermissionById(id);
                permission.Id = result.Id;
                permission.Key = result.Key;
                permission.PermissionTypeId = result.PermissionTypeId;

            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }

            return View(permission);
        }

        [HttpPost]
        public async Task<ActionResult> EditPermission(PermissionModel model)
        {
            try
            {
                await PermissionServiceClient.EditPermission(model.Id, model.Key, model.PermissionTypeId);

                return RedirectToAction("PermissionList");
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }
            return View();
        }

        public async Task<ActionResult> DeletePermission(long id)
        {
            var model =  new PermissionModel();
            try
            {
                var result = await PermissionServiceClient.GetPermissionById(id);
                model.Id = result.Id;
                model.Key = result.Key;
                model.PermissionTypeId = result.PermissionTypeId;
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> DeletePermission(PermissionModel model)
        {
            try
            {
                await PermissionServiceClient.DeletePermission(model.Id);

                return RedirectToAction("PermissionList");
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }
            return View(model);
        }
    }
}

Master/WebUi/Controllers/LoginController.cs
using GalaSoft.MvvmLight.Ioc;
using Server.Infrastructure.Dto;
using System;
using System.Net;
using System.Net.Mail;
using System.ServiceModel;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebUi.Model.Login;
using WebUiServiceClient.User;
using System.Security.Claims;

namespace WebUi.Controllers
{
    public class LoginController : Controller
    {
        private IUserServiceClient _userServiceClient;

        private IUserServiceClient UserServiceClient => _userServiceClient ?? (_userServiceClient = SimpleIoc.Default.GetInstance<IUserServiceClient>());

        // GET: Login
        public  ActionResult Index()
        {
            var model = new LoginViewModel();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(LoginViewModel loginRequest)
        {
            var role = new RoleDto();
           
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await UserServiceClient.Login(loginRequest.Email, loginRequest.Password);
                    Session["User"] = user.Email;

                    role = await UserServiceClient.GetRoleTypeId(user.Email);
                    Session["Role"] = role.Key;

                    if (role.Key == "Admin")
                    {
                        return RedirectToAction("Index", "Admin");
                    }
                    else if (role.Key == "User")
                    {
                        return RedirectToAction("Index", "User");
                    }
                    else
                    {
                        return RedirectToAction("Index", "Client");
                    }
                }
                catch (Exception e)
                {
                    ViewBag.Error = "Sikertelen Belépés!!";
                }
            }
      
            return View();
        }

        public ActionResult Logout()
        {
            Session.Remove("User");
            Session.Remove("Role");

            return RedirectToAction("Index");
        }

        public ActionResult ForgotPassword()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<ActionResult> ForgotPassword(ForgotPasswordViewModel forgotPasswordViewModel)
        {
            if (forgotPasswordViewModel.Email != null)
            {
                try
                {
                    await UserServiceClient.Forgot(forgotPasswordViewModel.Email);
                    string token = Convert.ToBase64String(Guid.NewGuid().ToByteArray());
                    // todo : saját mail címre küldje a levelet
                    SendResetLinkEmail(forgotPasswordViewModel.Email);
                    ViewBag.Message = "Jelszó visszaállító link elküdve!";
                }
                catch (Exception e)
                {
                    ViewBag.Error = e.Message;
                }
            }
            
            return View();
        }
        public ActionResult ResetPassword()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public  ActionResult ResetPassword(ForgotPasswordViewModel forgotPassword)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    UserServiceClient.ResetPassword(forgotPassword.Email, forgotPassword.Password,forgotPassword.Token);
                    ViewBag.Message = "A jelszó visszaállítás sikeresen megtörtént :) ";
                }
                catch (Exception e)
                {
                    ViewBag.Error = e.Message;
                }
            }

            return View();
        }

        [ValidateAntiForgeryToken]
        [NonAction]
        public void SendResetLinkEmail(string email)
        {
            // todo: admin email 
            var token = Guid.NewGuid();
            var tokenExpiration = TimeSpan.FromDays(1);

            var fromEmail = new MailAddress("info.creativeteams@gmail.com", "TimeTracker");
            var toEmail = new MailAddress(email);
            var fromEmailPassword = "KD0223kd#";
    
            string uri = "Login/ResetPassword";

            string link = @"http://localhost:56359/"+uri+"/"+token;
            string subject = "Reset Password";
            string body = "Hi,<br/><br/>We got request for reset your account password. Please click on the below link to reset your password" +
                          "<br/><br/><a href=" + link + ">Reset Password link</a>";

            try
            {
                var smtp = new SmtpClient
                {
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    UseDefaultCredentials = false,
                    Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
                };

                using (var message = new MailMessage(fromEmail, toEmail)
                {
                    Subject = subject,
                    Body = body,
                    IsBodyHtml = true
                })
                    smtp.Send(message);
            }
            catch (Exception e)
            {
                throw new FaultException("Nem sikerült az emailt elküldeni!");
            }
        }
    }
}

Master/WebUi/Views/AdminPermission/AddNewPermission.cshtml
@using DataAccessLayer
@model WebUi.Model.Permission.PermissionModel

@{
    ViewBag.Title = "AddNewPermission";
    Layout = "~/Views/Shared/_Admin_Layout.cshtml";
}
<br />
@if (Session["user"] == null)
{
    <p>@Html.ActionLink(@Resource.LoginPlease, "Index", "Login")</p>
}
else
{
    <h2>AddNewPermission</h2>
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <hr />
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <h4>@ViewBag.Message</h4>
                </div>
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Key, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Status", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.PermissionTypeId, new SelectList(Enum.GetValues(typeof(PermissionTypeEnum))), "  -- Select Permission Type --", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PermissionTypeId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    <div>
        @Html.ActionLink(WebUi.Resource.BackToList, "PermissionList", "AdminPermission")
    </div>
}
@section scripts
    {
    @Scripts.Render("~/bundles/jqueryval")
}

Master/WebUi/Views/AdminPermission/DeletePermission.cshtml
@model WebUi.Model.Permission.PermissionModel

@{
    ViewBag.Title = "DeletePermission";
    Layout = "~/Views/Shared/_Admin_Layout.cshtml";
}
<h2>Delete Permission</h2>
<h3>Are you sure you want to delete this?</h3>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        <h4><strong>@Model.Key</strong></h4>
        <div class="form-group">
            <div class="col-md-10">
                @ViewBag.Message
            </div>
        </div>
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-warning" /> |
            @Html.ActionLink(WebUi.Resource.BackToList, "PermissionList")
        </div>
    </div>
}

Master/WebUi/Views/AdminPermission/EditPermission.cshtml
@using DataAccessLayer
@model WebUi.Model.Permission.PermissionModel

@{
    ViewBag.Title = "EditPermission";
    Layout = "~/Views/Shared/_Admin_Layout.cshtml";
}
<h2>Edit Permission</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <h4>@ViewBag.Message</h4>
            </div>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Key, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Key, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Key, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Permission", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.PermissionTypeId, new SelectList(Enum.GetValues(typeof(PermissionTypeEnum))), "  -- Select Permission Type --", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PermissionTypeId, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
    <div>
        @Html.ActionLink(WebUi.Resource.BackToList, "PermissionList")
    </div>
}
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

Master/WebUi/Views/AdminPermission/PermissionList.cshtml
@model WebUi.Model.Permission.PermissionModel
@{
    ViewBag.Title = "GetAllPermission";
    Layout = "~/Views/Shared/_Admin_Layout.cshtml";
}
<br/>
@if (Session["user"] == null)
{
    <p>@Html.ActionLink(@Resource.LoginPlease, "Index", "Login")</p>
}
else
{
    <h2>@Resource.PermissionList</h2>
    <br/>
    <p>
        @Html.ActionLink(Resource.NewPermission, "AddNewPermission", null, new { @class = "btn btn-primary" })
    </p>
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @ViewBag.Message
            </div>
        </div>
        @if (Model.PermissionList.Count == 0)
        {
            <text> Clients list is empty.</text>
        }
        else
        {
            <div class="control-section">
                @Html.EJS().Grid("Grid").DataSource((IEnumerable<object>) @Model.PermissionList).AllowFiltering().FilterSettings(filter => filter.Type(Syncfusion.EJ2.Grids.FilterType.FilterBar)).Columns(col =>
                {
                    col.Field("Id").HeaderText("Id").Width("120").Add();
                    col.Field("Key").HeaderText(Model.Key).Width("auto").Add();
                    col.Field("PermissionTypeId").HeaderText("Permission Type Id").Width("auto").Add();
                    col.Field("Options").HeaderText("Options").Template("#template").Width("auto").Add();
                }).AllowPaging(true).AllowSorting().Created("created").Render()
            </div>
            <script id="template" type="text/x-template">
                <a rel='nofollow' href="EditPermission/${Id}">Edit</a> |
                <a rel='nofollow' href="DeletePermission/${Id}">Delete</a>
            </script>
            <script>
                function created() {
                    $(".e-filtertext").eq(0).attr("placeholder", "ID");
                    $(".e-filtertext").eq(1).attr("placeholder", "Key"); 
                    $(".e-filtertext").eq(2).attr("placeholder", "Permission type Id"); 
                }
            </script>
            <br />
            <div class="form-group">
                <div class="col-md-10">
                    @Html.ActionLink(WebUi.Resource.BackToHome, "Index", "Admin")
                </div>
            </div>
        }
    </div>
}