Master/WebUi/Controllers/AdminController.cs
using System;
using GalaSoft.MvvmLight.Ioc;
using System.Threading.Tasks;
using System.Web.Mvc;
using Server.Infrastructure.Dto.Requests.User;
using WebUi.Model.User;
using WebUiServiceClient.User;
using DataAccessLayer;

namespace WebUi.Controllers
{
    public class AdminController : Controller
    {
        private IUserServiceClient _userServiceClient;
        private IUserServiceClient UserServiceClient => _userServiceClient ?? (_userServiceClient = SimpleIoc.Default.GetInstance<IUserServiceClient>());

        // GET
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Info()
        {
            var user = new UserViewModel();

            if (Session["User"] != null)
            {
                try
                {
                    var result = await UserServiceClient.GetUserByEmail(Session["User"].ToString());

                    user.Name = result.Name;
                    user.Email = result.Email;
                    user.Phone = result.Phone;
                    user.RoleName = Enum.GetName(typeof(RoleTypeEnum), result.RoleId).ToString();
                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                }
            }

            return View(user);
        }

        public async Task<ActionResult> EditUser()
        {
            var user = new UserViewModel();

            if (Session["User"] != null)
            {
                try
                {
                    var result = await UserServiceClient.GetUserByEmail(Session["User"].ToString());

                    user.Id = result.Id;
                    user.Name = result.Name;
                    user.Email = result.Email;
                    user.Phone = result.Phone;
                    user.RoleName = result.RoleName;
                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                }
            }

            return View(user);
        }

        [HttpPost]
        public async Task<ActionResult> EditUser(UserViewModel model)
        {
            var request = new AddUserRequest
            {
                Id = model.Id,
                Name = model.Name,
                Email = model.Email,
                Phone = model.Phone,
                Password = model.Password
            };

            try
            {
                var result = await UserServiceClient.EditUser(request);

                ViewBag.Message = "Done :)";
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }

            return View();
        }
    }
}

Master/WebUi/Controllers/LoginController.cs
using GalaSoft.MvvmLight.Ioc;
using Server.Infrastructure.Dto;
using System;
using System.Net;
using System.Net.Mail;
using System.ServiceModel;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebUi.Model.Login;
using WebUiServiceClient.User;
using System.Security.Claims;

namespace WebUi.Controllers
{
    public class LoginController : Controller
    {
        private IUserServiceClient _userServiceClient;

        private IUserServiceClient UserServiceClient => _userServiceClient ?? (_userServiceClient = SimpleIoc.Default.GetInstance<IUserServiceClient>());

        // GET: Login
        public  ActionResult Index()
        {
            var model = new LoginViewModel();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(LoginViewModel loginRequest)
        {
            var role = new RoleDto();
           
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await UserServiceClient.Login(loginRequest.Email, loginRequest.Password);
                    Session["User"] = user.Email;

                    role = await UserServiceClient.GetRoleTypeId(user.Email);
                    Session["Role"] = role.Key;

                    if (role.Key == "Admin")
                    {
                        return RedirectToAction("Index", "Admin");
                    }
                    else if (role.Key == "User")
                    {
                        return RedirectToAction("Index", "User");
                    }
                    else
                    {
                        return RedirectToAction("Index", "Client");
                    }
                }
                catch (Exception e)
                {
                    ViewBag.Error = "Sikertelen Belépés!!";
                }
            }
      
            return View();
        }

        public ActionResult Logout()
        {
            Session.Remove("User");
            Session.Remove("Role");

            return RedirectToAction("Index");
        }

        public ActionResult ForgotPassword()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<ActionResult> ForgotPassword(ForgotPasswordViewModel forgotPasswordViewModel)
        {
            if (forgotPasswordViewModel.Email != null)
            {
                try
                {
                    await UserServiceClient.Forgot(forgotPasswordViewModel.Email);
                    string token = Convert.ToBase64String(Guid.NewGuid().ToByteArray());
                    // todo : saját mail címre küldje a levelet
                    SendResetLinkEmail(forgotPasswordViewModel.Email);
                    ViewBag.Message = "Jelszó visszaállító link elküdve!";
                }
                catch (Exception e)
                {
                    ViewBag.Error = e.Message;
                }
            }
            
            return View();
        }
        public ActionResult ResetPassword()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public  ActionResult ResetPassword(ForgotPasswordViewModel forgotPassword)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    UserServiceClient.ResetPassword(forgotPassword.Email, forgotPassword.Password,forgotPassword.Token);
                    ViewBag.Message = "A jelszó visszaállítás sikeresen megtörtént :) ";
                }
                catch (Exception e)
                {
                    ViewBag.Error = e.Message;
                }
            }

            return View();
        }

        [ValidateAntiForgeryToken]
        [NonAction]
        public void SendResetLinkEmail(string email)
        {
            // todo: admin email 
            var token = Guid.NewGuid();
            var tokenExpiration = TimeSpan.FromDays(1);

            var fromEmail = new MailAddress("info.creativeteams@gmail.com", "TimeTracker");
            var toEmail = new MailAddress(email);
            var fromEmailPassword = "KD0223kd#";
    
            string uri = "Login/ResetPassword";

            string link = @"http://localhost:56359/"+uri+"/"+token;
            string subject = "Reset Password";
            string body = "Hi,<br/><br/>We got request for reset your account password. Please click on the below link to reset your password" +
                          "<br/><br/><a href=" + link + ">Reset Password link</a>";

            try
            {
                var smtp = new SmtpClient
                {
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    UseDefaultCredentials = false,
                    Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
                };

                using (var message = new MailMessage(fromEmail, toEmail)
                {
                    Subject = subject,
                    Body = body,
                    IsBodyHtml = true
                })
                    smtp.Send(message);
            }
            catch (Exception e)
            {
                throw new FaultException("Nem sikerült az emailt elküldeni!");
            }
        }
    }
}

Master/WebUi/Controllers/ProjectController.cs
using GalaSoft.MvvmLight.Ioc;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebUi.Model.Client;
using WebUi.Model.Project;
using WebUi.Model.Team;
using WebUi.ViewModel.Todo;
using WebUiServiceClient.Client;
using WebUiServiceClient.Project;
using WebUiServiceClient.Team;
using WebUiServiceClient.Todo;
using WebUiServiceClient.User;

namespace WebUi.Controllers
{
    public class ProjectController : Controller
    {
        private IProjectServiceClient _projectServiceClient;
        private IProjectServiceClient ProjectServiceClient => _projectServiceClient ?? (_projectServiceClient = SimpleIoc.Default.GetInstance<IProjectServiceClient>());

        private IUserServiceClient _userServiceClient;
        private IUserServiceClient UserServiceClient => _userServiceClient ?? (_userServiceClient = SimpleIoc.Default.GetInstance<IUserServiceClient>());

        private ITeamServiceClient _teamServiceClient;
        private ITeamServiceClient TeamServiceClient => _teamServiceClient ?? (_teamServiceClient = SimpleIoc.Default.GetInstance<ITeamServiceClient>());

        private IClientServicClient _clientServicClient;
        private IClientServicClient ClientServicClient => _clientServicClient ?? (_clientServicClient = SimpleIoc.Default.GetInstance<IClientServicClient>());

        private ITodoServiceClient _todoServiceClient;
        private ITodoServiceClient TodoServiceClient => _todoServiceClient ?? (_todoServiceClient = SimpleIoc.Default.GetInstance<ITodoServiceClient>());

        // GET
        public ActionResult Index()
        {
            return
            View();
        }

        public async Task<ActionResult> DetailsProjectList(long id)
        {
            var model = new ProjectViewModel();
            try
            {
                model.ProjectDetails = await ProjectServiceClient.GetDetailsProjectById(id);
                model.AllTodoList = await TodoServiceClient.GetTodoByProjectId(model.ProjectDetails.TeamId);
                if (model.AllTodoList.Count >= 1)
                {
                    ViewBag.Flag = "1";
                }
                else
                {
                    ViewBag.Flag = "0";
                }


            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }

            return View(model);
        }

        public async Task<ActionResult> ProjectList()
        {
            var modelView = new ProjectViewModel();

            if (Session["User"] != null)
            {
                var userEmail = Session["User"].ToString();

                try
                {
                    if (Session["Role"].ToString() == "Client")
                    {

                        modelView.ProjectList = await ProjectServiceClient.GetAllProjectByClient(userEmail);
                    }
                    else
                    {
                        modelView.ProjectList = await ProjectServiceClient.GetAllProjectByUser(userEmail);
                    }
                }

                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                }
            }

            return View(modelView);
        }

        [HttpPost]
        public async Task<ActionResult> ProjectList(ProjectViewModel model)
        {
            if (Session["User"] != null)
            {
                var userEmail = Session["User"].ToString();

                try
                {
                    model.TeamList = await TeamServiceClient.GetTeamsToUser(userEmail);
                    model.TeamListForTeam = await ProjectServiceClient.GetAllProjectByTeamId(model.TeamId);
                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                }
            }

            return View(model);
        }

        public async Task<ActionResult> DetailsTeam(long id)
        {
            var model = new TeamDetailsViewModel();

            try
            {
                model.TeamDetailsList = await TeamServiceClient.GetTeamDetails(id);
                model.TeamName = model.TeamDetailsList[0].TeamName;
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }

            return View(model);
        }

        public async Task<ActionResult> DetailsClient(long id)
        {
            var model = new ClientDetailsViewModel();

            try
            {
                model.ClientDetails = await ClientServicClient.GetDetailsClientById(id);
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }

            return View(model);
        }

        public async Task<ActionResult> TodoListByTeamId()
        {
            var model = new TodoViewModel();

            try
            {
                //var result = await TodoServiceClient.GetTodoByTeamId(id);
                model.TodoList = await TodoServiceClient.GetAllTodo();
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }
            return View();
        }
    }
}

Master/WebUi/Controllers/RegisterController.cs
using GalaSoft.MvvmLight.Ioc;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebUi.Model.Register;
using WebUiServiceClient.Client;
using WebUiServiceClient.Team;
using WebUiServiceClient.User;

namespace WebUi.Controllers
{
    public class RegisterController : Controller
    {
        private IUserServiceClient _userServiceClient;
        private IUserServiceClient UserServiceClient => _userServiceClient ?? (_userServiceClient = SimpleIoc.Default.GetInstance<IUserServiceClient>());

        private ITeamServiceClient _teamServiceClient;
        private ITeamServiceClient TeamServiceClient => _teamServiceClient ?? (_teamServiceClient = SimpleIoc.Default.GetInstance<ITeamServiceClient>());

        private IClientServicClient _clientServicClient;
        private IClientServicClient ClientServicClient => _clientServicClient ?? (_clientServicClient = SimpleIoc.Default.GetInstance<IClientServicClient>());

        // GET: RegisterUser
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> RegisterUser()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> RegisterUser(AddUserRequestView addUserUserRequest)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var reult = await  UserServiceClient.RegisterUser(addUserUserRequest);
                    
                    if (Session["User"] != null && Session["Role"].ToString() == "Admin")
                    {
                        return RedirectToAction("Index", "Admin");
                    }
                    else
                    {
                        ViewBag.Message = "Siker :)";

                        ModelState.Clear();
                    } 
                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                }
            }
            return View();
        }

        
        public async Task<ActionResult> RegisterClient()
        {
            var modelView = new AddClientRequestView();

            if (Session["User"] != null && Session["Role"].ToString() == "Admin")
            { 
                try
                {
                    modelView.TeamListForUser = await TeamServiceClient.GetAllTeam();
                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                }
            }

            return View(modelView);
        }

        [HttpPost]
        public async Task<ActionResult> RegisterClient(AddClientRequestView addClientRequest)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    await ClientServicClient.RegisterClient(addClientRequest);
                    ViewBag.Message = "Done :)";

                    //return RedirectToAction("RegisterClient");
                }
                catch (Exception e)
                {
                    ViewBag.Message = "Sikertelen regisztráció!!";
                }
            }

            addClientRequest.TeamListForUser = await TeamServiceClient.GetAllTeam();

            return View(addClientRequest);
        }
    }
}

Master/WebUi/Views/Shared/_Admin_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Time Track</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/ej2/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/ej2/ej2.min.js"></script>
    <link href="~/Content/ej2/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(WebUi.Resource.Home, "Index", "Admin", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            @if (Session["User"] != null && Session["Role"].ToString() == "Admin")
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink(WebUi.Resource.Clients, "ClientsList", "AdminClient")</li>
                        <li>@Html.ActionLink(WebUi.Resource.Users, "UserList", "AdminUser")</li>
                        <li>@Html.ActionLink(WebUi.Resource.Teams, "TeamList", "Team")</li>
                        <li>@Html.ActionLink(WebUi.Resource.Projects, "ProjectList", "AdminProject")</li>
                        <li>@Html.ActionLink(WebUi.Resource.Status, "StatusList", "AdminStatus")</li>
                        <li>@Html.ActionLink(WebUi.Resource.Currency, "CurrencyList", "AdminCurrency")</li>
                        <li>@Html.ActionLink(WebUi.Resource.Permission, "PermissionList", "AdminPermission")</li>
                        <li>@Html.ActionLink(WebUi.Resource.Role, "RoleList", "AdminRole")</li>
                        @*<li>@Html.ActionLink("Time Record","Addtimerecord", "TimeRecord")</li>*@
                        <li>@Html.ActionLink("Todo", "TodoList", "AdminTodo")</li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">

                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                @Session["User"].ToString()
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a>@Html.ActionLink(WebUi.Resource.Profile, "Info", "Admin")</a></li>
                                <li>@Html.ActionLink(WebUi.Resource.EditProfile, "EditUser", "Admin")</li>
                            </ul>
                        </li>

                        <li>@Html.ActionLink(WebUi.Resource.LogOut, "Logout", "Login")</li>
                    </ul>

                </div>
            }
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Time Track</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Html.EJS().ScriptManager()
</body>
</html>

Master/WebUi/Views/Shared/_Client_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Time Track</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/ej2/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/ej2/ej2.min.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(WebUi.Resource.Home, "Index", "Client", new {area = ""}, new {@class = "navbar-brand"})
            </div>

            <div class="navbar-collapse collapse">

                @if (Session["User"] != null && Session["Role"].ToString() == "Client")
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink(WebUi.Resource.Projects, "ProjectList", "Project")</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink(Session["User"].ToString(), "Index", "Client")</li>
                        <li>@Html.ActionLink(WebUi.Resource.LogOut, "Logout", "Login")</li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Time Track</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <!-- Syncfusion Essential JS 2 ScriptManager -->
    @Html.EJS().ScriptManager()
</body>
</html>

Master/WebUi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Time Track</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/ej2/bootstrap4.css" rel="stylesheet" />
    <script src="~/Scripts/ej2/ej2.min.js"></script>
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(WebUi.Resource.ApplicationName, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(WebUi.Resource.Home, "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink(WebUi.Resource.Contact, "Contact", "Home")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink(WebUi.Resource.Login, "Index", "Login")</li>
                    <li>@Html.ActionLink(WebUi.Resource.Register, "RegisterUser", "Register")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Time Track</p>
        </footer>
    </div>

    <div style="padding:5px">

        @{
            foreach (var i in WebUi.Model.Language.Language.AvailableLanguages)
            {
                @Html.ActionLink(i.LanguageFullName, "ChangeLanguage", "Home", new { lang = i.LanguageCultureName }, null) <text> </text>
            }
        }
    </div>


    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
    @Html.EJS().ScriptManager()
</body>
</html>

Master/WebUi/Views/Shared/_User_layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Time Track</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/bootstrap4.css" rel="stylesheet" />
    <script src="~/Scripts/ej2/ej2.min.js"></script>
    <link href="~/Content/ej2/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(WebUi.Resource.Home, "Index", "User", new {area = ""}, new {@class = "navbar-brand"})
            </div>
            <div class="navbar-collapse collapse">

                @if (Session["User"] != null && Session["Role"].ToString() == "User")
                {
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink(WebUi.Resource.Clients, "ClientsList", "Client")</li>
                        <li>@Html.ActionLink(WebUi.Resource.Teams, "TeamList", "Team")</li>
                        <li>@Html.ActionLink(WebUi.Resource.Projects, "ProjectList", "Project")</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">

                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                @Session["User"].ToString()
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a>@Html.ActionLink(WebUi.Resource.Profile, "Info", "User")</a></li>
                                <li>@Html.ActionLink(WebUi.Resource.EditProfile, "EditUser", "User")</li>
                            </ul>
                        </li>

                        <li>@Html.ActionLink(WebUi.Resource.LogOut, "Logout", "Login")</li>
                    </ul>
                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Time Track</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Html.EJS().ScriptManager()
</body>
</html>