Master/WebUi/Controllers/AdminController.cs
using System;
using GalaSoft.MvvmLight.Ioc;
using System.Threading.Tasks;
using System.Web.Mvc;
using Server.Infrastructure.Dto.Requests.User;
using WebUi.Model.User;
using WebUiServiceClient.User;
using DataAccessLayer;

namespace WebUi.Controllers
{
    public class AdminController : Controller
    {
        private IUserServiceClient _userServiceClient;
        private IUserServiceClient UserServiceClient => _userServiceClient ?? (_userServiceClient = SimpleIoc.Default.GetInstance<IUserServiceClient>());

        // GET
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Info()
        {
            var user = new UserViewModel();

            if (Session["User"] != null)
            {
                try
                {
                    var result = await UserServiceClient.GetUserByEmail(Session["User"].ToString());

                    user.Name = result.Name;
                    user.Email = result.Email;
                    user.Phone = result.Phone;
                    user.RoleName = Enum.GetName(typeof(RoleTypeEnum), result.RoleId).ToString();
                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                }
            }

            return View(user);
        }

        public async Task<ActionResult> EditUser()
        {
            var user = new UserViewModel();

            if (Session["User"] != null)
            {
                try
                {
                    var result = await UserServiceClient.GetUserByEmail(Session["User"].ToString());

                    user.Id = result.Id;
                    user.Name = result.Name;
                    user.Email = result.Email;
                    user.Phone = result.Phone;
                    user.RoleName = result.RoleName;
                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                }
            }

            return View(user);
        }

        [HttpPost]
        public async Task<ActionResult> EditUser(UserViewModel model)
        {
            var request = new AddUserRequest
            {
                Id = model.Id,
                Name = model.Name,
                Email = model.Email,
                Phone = model.Phone,
                Password = model.Password
            };

            try
            {
                var result = await UserServiceClient.EditUser(request);

                ViewBag.Message = "Done :)";
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }

            return View();
        }
    }
}

Master/WebUi/Controllers/AdminUserController.cs
using GalaSoft.MvvmLight.Ioc;
using Server.Infrastructure.Dto.Requests.User;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebUi.Model.User;
using WebUiServiceClient.Role;
using WebUiServiceClient.User;

namespace WebUi.Controllers
{
    public class AdminUserController : Controller
    {
        private IUserServiceClient _userServiceClient;
        private IUserServiceClient UserServiceClient => _userServiceClient ?? (_userServiceClient = SimpleIoc.Default.GetInstance<IUserServiceClient>());

        private IRoleServiceClient _roleServicClient;
        private IRoleServiceClient RoleServiceClient => _roleServicClient ?? (_roleServicClient = SimpleIoc.Default.GetInstance<IRoleServiceClient>());

        // GET: AdminUser
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> UserList()
        {
            var user = new UserViewModel();

            try
            {
                user.UserList = await UserServiceClient.GetAllUser();
                
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }

            return View(user);
        }

        public async Task<ActionResult> EditUser(long id)
        {
            var model = new UserViewModel();

            try
            {
                var result = await UserServiceClient.GetUserById(id);
                model.RoleList = await RoleServiceClient.GetAllRole();

                model.Id = result.Id;
                model.Name = result.Name;
                model.Email = result.Email;
                model.Phone = result.Phone;
                model.RoleId = result.RoleId;
                model.RoleName = result.RoleName;
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> EditUser(UserViewModel model)
        {

            var user = new AddUserRequest
            {
                Id = model.Id,
                Name = model.Name,
                Email = model.Email,
                Phone = model.Phone,
                RoleId = model.RoleId,
                Password = model.Password
            };

            try
            {
                var result = await UserServiceClient.EditUser(user);

                return RedirectToAction("UserList");
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }
            return View(model);
        }

        public async Task<ActionResult> DeleteUser(long id)
        {
            var user = new UserViewModel();

            try
            {
                var result = await UserServiceClient.GetUserById(id);
                user.Id = result.Id;
                user.Name = result.Name;
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }
            return View(user);
        }

        [HttpPost]
        public async Task<ActionResult> DeleteUser(UserViewModel model)
        {
            try
            {
                var result = await UserServiceClient.DeleteUser(model.Id);

                return RedirectToAction("UserList");
            }
            catch (Exception e)
            {
                ViewBag.Message = e.Message;
            }

            return View(model);
        }
    }
}

Master/WebUi/Controllers/LoginController.cs
using GalaSoft.MvvmLight.Ioc;
using Server.Infrastructure.Dto;
using System;
using System.Net;
using System.Net.Mail;
using System.ServiceModel;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebUi.Model.Login;
using WebUiServiceClient.User;
using System.Security.Claims;

namespace WebUi.Controllers
{
    public class LoginController : Controller
    {
        private IUserServiceClient _userServiceClient;

        private IUserServiceClient UserServiceClient => _userServiceClient ?? (_userServiceClient = SimpleIoc.Default.GetInstance<IUserServiceClient>());

        // GET: Login
        public  ActionResult Index()
        {
            var model = new LoginViewModel();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(LoginViewModel loginRequest)
        {
            var role = new RoleDto();
           
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await UserServiceClient.Login(loginRequest.Email, loginRequest.Password);
                    Session["User"] = user.Email;

                    role = await UserServiceClient.GetRoleTypeId(user.Email);
                    Session["Role"] = role.Key;

                    if (role.Key == "Admin")
                    {
                        return RedirectToAction("Index", "Admin");
                    }
                    else if (role.Key == "User")
                    {
                        return RedirectToAction("Index", "User");
                    }
                    else
                    {
                        return RedirectToAction("Index", "Client");
                    }
                }
                catch (Exception e)
                {
                    ViewBag.Error = "Sikertelen Belépés!!";
                }
            }
      
            return View();
        }

        public ActionResult Logout()
        {
            Session.Remove("User");
            Session.Remove("Role");

            return RedirectToAction("Index");
        }

        public ActionResult ForgotPassword()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<ActionResult> ForgotPassword(ForgotPasswordViewModel forgotPasswordViewModel)
        {
            if (forgotPasswordViewModel.Email != null)
            {
                try
                {
                    await UserServiceClient.Forgot(forgotPasswordViewModel.Email);
                    string token = Convert.ToBase64String(Guid.NewGuid().ToByteArray());
                    // todo : saját mail címre küldje a levelet
                    SendResetLinkEmail(forgotPasswordViewModel.Email);
                    ViewBag.Message = "Jelszó visszaállító link elküdve!";
                }
                catch (Exception e)
                {
                    ViewBag.Error = e.Message;
                }
            }
            
            return View();
        }
        public ActionResult ResetPassword()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public  ActionResult ResetPassword(ForgotPasswordViewModel forgotPassword)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    UserServiceClient.ResetPassword(forgotPassword.Email, forgotPassword.Password,forgotPassword.Token);
                    ViewBag.Message = "A jelszó visszaállítás sikeresen megtörtént :) ";
                }
                catch (Exception e)
                {
                    ViewBag.Error = e.Message;
                }
            }

            return View();
        }

        [ValidateAntiForgeryToken]
        [NonAction]
        public void SendResetLinkEmail(string email)
        {
            // todo: admin email 
            var token = Guid.NewGuid();
            var tokenExpiration = TimeSpan.FromDays(1);

            var fromEmail = new MailAddress("info.creativeteams@gmail.com", "TimeTracker");
            var toEmail = new MailAddress(email);
            var fromEmailPassword = "KD0223kd#";
    
            string uri = "Login/ResetPassword";

            string link = @"http://localhost:56359/"+uri+"/"+token;
            string subject = "Reset Password";
            string body = "Hi,<br/><br/>We got request for reset your account password. Please click on the below link to reset your password" +
                          "<br/><br/><a href=" + link + ">Reset Password link</a>";

            try
            {
                var smtp = new SmtpClient
                {
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    UseDefaultCredentials = false,
                    Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
                };

                using (var message = new MailMessage(fromEmail, toEmail)
                {
                    Subject = subject,
                    Body = body,
                    IsBodyHtml = true
                })
                    smtp.Send(message);
            }
            catch (Exception e)
            {
                throw new FaultException("Nem sikerült az emailt elküldeni!");
            }
        }
    }
}

Master/WebUi/Controllers/RegisterController.cs
using GalaSoft.MvvmLight.Ioc;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebUi.Model.Register;
using WebUiServiceClient.Client;
using WebUiServiceClient.Team;
using WebUiServiceClient.User;

namespace WebUi.Controllers
{
    public class RegisterController : Controller
    {
        private IUserServiceClient _userServiceClient;
        private IUserServiceClient UserServiceClient => _userServiceClient ?? (_userServiceClient = SimpleIoc.Default.GetInstance<IUserServiceClient>());

        private ITeamServiceClient _teamServiceClient;
        private ITeamServiceClient TeamServiceClient => _teamServiceClient ?? (_teamServiceClient = SimpleIoc.Default.GetInstance<ITeamServiceClient>());

        private IClientServicClient _clientServicClient;
        private IClientServicClient ClientServicClient => _clientServicClient ?? (_clientServicClient = SimpleIoc.Default.GetInstance<IClientServicClient>());

        // GET: RegisterUser
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> RegisterUser()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> RegisterUser(AddUserRequestView addUserUserRequest)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var reult = await  UserServiceClient.RegisterUser(addUserUserRequest);
                    
                    if (Session["User"] != null && Session["Role"].ToString() == "Admin")
                    {
                        return RedirectToAction("Index", "Admin");
                    }
                    else
                    {
                        ViewBag.Message = "Siker :)";

                        ModelState.Clear();
                    } 
                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                }
            }
            return View();
        }

        
        public async Task<ActionResult> RegisterClient()
        {
            var modelView = new AddClientRequestView();

            if (Session["User"] != null && Session["Role"].ToString() == "Admin")
            { 
                try
                {
                    modelView.TeamListForUser = await TeamServiceClient.GetAllTeam();
                }
                catch (Exception e)
                {
                    ViewBag.Message = e.Message;
                }
            }

            return View(modelView);
        }

        [HttpPost]
        public async Task<ActionResult> RegisterClient(AddClientRequestView addClientRequest)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    await ClientServicClient.RegisterClient(addClientRequest);
                    ViewBag.Message = "Done :)";

                    //return RedirectToAction("RegisterClient");
                }
                catch (Exception e)
                {
                    ViewBag.Message = "Sikertelen regisztráció!!";
                }
            }

            addClientRequest.TeamListForUser = await TeamServiceClient.GetAllTeam();

            return View(addClientRequest);
        }
    }
}

Master/WebUi/Views/AdminUser/DeleteUser.cshtml
@model WebUi.Model.User.UserViewModel

@{
    ViewBag.Title = "DeleteUser";
    Layout = "~/Views/Shared/_Admin_Layout.cshtml";
}
<h2>Delete User</h2>
<h3>Are you sure you want to delete this?</h3>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        <h4><strong>@Model.Name</strong></h4>
        <div class="form-group">
            <div class="col-md-10">
                @ViewBag.Message
            </div>
        </div>
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-warning" /> |
            @Html.ActionLink(WebUi.Resource.BackToList, "UserList")
        </div>

    </div>
}

Master/WebUi/Views/AdminUser/EditUser.cshtml
@model WebUi.Model.User.UserViewModel

@{
    ViewBag.Title = "EditUser";
    Layout = "~/Views/Shared/_Admin_Layout.cshtml";
}
<br />
@using (Html.BeginForm("EditUser", "AdminUser"))
{
    @Html.AntiForgeryToken()
    <h2>Edit @Model.Name</h2>
    <div class="form-horizontal">
        <hr/>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <h4>@ViewBag.Message</h4>
            </div>
        </div>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Email, "", new {@class = "text-danger"})
            </div>
        </div>
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Phone, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.Password, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.PasswordFor(model => model.ConfirmPassword, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.RoleName, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.RoleId, new SelectList(Model.RoleList, "Id", "Key", @Model.RoleId), @Model.RoleName, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.RoleId, "", new {@class = "text-danger"})
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </div>
    </div>
    <div>
        @Html.ActionLink(WebUi.Resource.BackToList, "UserList")
    </div>
}
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

Master/WebUi/Views/AdminUser/UserList.cshtml
@model WebUi.Model.User.UserViewModel

@{
    ViewBag.Title = "UserList";
    Layout = "~/Views/Shared/_Admin_Layout.cshtml";
}
<br/>
@if (Session["user"] == null)
{
    <p>@Html.ActionLink(@Resource.LoginPlease, "Index", "Login")</p>
}
else
{
    <h2>@Resource.UserList</h2>
    <p>
        @Html.ActionLink(Resource.CreateNewUser, "RegisterUser", "Register", null, new { @class = "btn btn-primary" })
    </p>
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @ViewBag.Message
            </div>
        </div>
        @if (Model.UserList.Count == 0)
        {
            <text> Clients list is empty.</text>
        }
        else
        {
            <div class="control-section">
                @Html.EJS().Grid("Grid").DataSource((IEnumerable<object>) @Model.UserList).AllowFiltering().FilterSettings(filter => filter.Type(Syncfusion.EJ2.Grids.FilterType.FilterBar)).Columns(col =>
                {
                    col.Field("Id").HeaderText("Id").Width("120").Add();
                    col.Field("Name").HeaderText(Model.Name).Width("auto").Add();
                    col.Field("Email").HeaderText(Model.Email).Width("auto").Add();
                    col.Field("Phone").HeaderText(Model.Phone).Width("auto").Add();
                    col.Field("RoleName").HeaderText(Model.RoleName).Width("auto").Add();
                    col.Field("Options").HeaderText("Options").Template("#template").Width("auto").Add();
                }).AllowPaging(true).AllowSorting().Created("created").Render()
            </div>
            <script id="template" type="text/x-template">
                <a rel='nofollow' href="EditUser/${Id}">Edit</a> |
                <a rel='nofollow' href="DeleteUser/${Id}">Delete</a>
            </script>
            <script>
                function created() {
                    $(".e-filtertext").eq(0).attr("placeholder", "ID");
                    $(".e-filtertext").eq(1).attr("placeholder", "Name");
                    $(".e-filtertext").eq(2).attr("placeholder", "Email");
                    $(".e-filtertext").eq(3).attr("placeholder", "Phone");
                    $(".e-filtertext").eq(4).attr("placeholder", "Role Name");
                }
            </script>
            <br />
            <div class="form-group">
                <div class="col-md-10">
                    @Html.ActionLink(WebUi.Resource.BackToHome, "Index", "Admin")
                </div>
            </div>
            <div id="Grid"></div> 
        }
    </div>
}